name: Lint and test code
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  e2e-test:
    name: E2E test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [ "1.23.15", "1.24.12", "1.25.8", "1.26.1" ]
    env:
      DOCKER_BUILDKIT: '1' # Setting DOCKER_BUILDKIT=1 ensures TARGETOS and TARGETARCH are populated
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.29.0'
          kubernetes version: ${{ matrix.k8s-version }}
          driver: docker
          start args: '--force'
      - name: Run e2e test
        continue-on-error: true
        run: |
          # make minikube use local docker registry
          eval $(minikube -p minikube docker-env)

          # create a docker image and use it in minikube
          DOCKER_IMAGE_TAG=e2e-test make e2e-test
