name: Release
on:
  release:
    types:
      - prereleased
      - released

jobs:
  publish:
    name: Release docker images
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: cribl/k8s-webhook-cert-manager
      DOCKER_PLATFORMS: "linux/amd64,linux/arm64,linux/arm"
    steps:
      - uses: actions/checkout@v3

      - name: Generate docker image version from git tag
        run: |
          echo "${{ github.event.release.tag_name }}" | grep -E '^v[0-9.]*[0-9]-?.*?$'
          DOCKER_IMAGE_TAG=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV

      - if: ${{ github.event.release.prerelease }}
        run: |
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}-pre" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: scopeci
          password: ${{ secrets.SCOPECI_TOKEN }}

      - name: Build and push docker image
        run: |
          docker buildx build --push --platform=$DOCKER_PLATFORMS \
            -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG \
            .
      - name: Push :latest image
        if: ${{ ! github.event.release.prerelease }}
        run: |
          docker buildx build --push --platform=$DOCKER_PLATFORMS \
            -t $DOCKER_IMAGE_NAME:latest \
            .
